### ISSUE TITLE
Feature Request: Change the gamemode of a player on an event (Is this already in here?)

### ISSUE THREAD

**Issue by Razorskills** [ModDamage/ModDamage#219]
Basically I am trying to set moddamage to change the gamemode of a player if it is equal to 1 back to 0 on joining the server. Or back to 1 on a different event that could be set later on.

**Comment by coaster3000** [comment]
Solution was given, feature is already implemented. 

_Cleaning up issue tracker_

**Comment by Razorskills** [comment]
Holly crap this is an old Issue.

**Comment by coaster3000** [comment]
Indeed, just haven't been closed when it was supposed to be.
